name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file XYZ-Stats/XYZ-Stats.API/Dockerfile --tag XYZ-Stats:$(date +%s)
      run: docker build . --file API/Dockerfile --tag my-image-name:$(date +%s)
